version: "2.4"

services:
  livebook:
    image: ghcr.io/livebook-dev/livebook
    container_name: livebook
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - LIVEBOOK_PORT=8080
      - LIVEBOOK_IFRAME_PORT=8081
      - LIVEBOOK_TOKEN_ENABLED=false
    volumes:
      - .:/data
  db:
    container_name: postgres
    build: 
      context: .
      dockerfile: docker/postgis.Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roadbook_dev
    ports:
      - 5432:5432